title: James Poeschel # your name (or website title) here
logo: "/images/IMG_9270.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p><Strong>GIS Analyst for Mead & Hunt </p>
  <br><br>
  <p>Multilingual Mapping enthusiast
  <br> Current Penn State student for Graduate Certificate in Geospatial Programming and Web Map Development
  <br> UMBC Bachelors in Geography and Environmental Science
  <br> UMBC Certificate in GISceince
  </p>
  <br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
