title: James Poeschel # your name (or website title) here
logo: "/images/IMG_9270.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p><strong>GIS Analyst at Mead & Hunt </strong></p>
  <br>
  <p> Hello, I am a GIS enthusiast that has a passion for conservation, ecology, and international development. I speak Portuguese, Spanish, French, and Korean. </p>
  <br><br>
  <p style="font-size: 12px;"> Current Penn State student for Graduate Certificate in Geospatial Programming and Web Map Development
  <br> UMBC Bachelors in Geography and Environmental Science & Certificate in GIScience
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
