title: James Poeschel # your name (or website title) here
logo: "/images/IMG_9270.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p><strong>GIS Analyst at Mead & Hunt </strong></p>
  <br><br>
  <p> Hello, I am a GIS and mapping enthusiast that is passionate in conservation, ecology, and international development. I speak Portuguese and English at the advanced level and Spanish, French, and Korean at an intermediate level. 
  <br><br><br> Current Penn State student for Graduate Certificate in Geospatial Programming and Web Map Development
  <br> UMBC Bachelors in Geography and Environmental Science
  <br> UMBC Certificate in GISceince
  </p>
  <br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
